# Generated by Django 4.2.6 on 2023-11-05 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_remove_clinic_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
