# Generated by Django 4.2.6 on 2023-11-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='location',
        ),
    ]
