# Generated by Django 4.2.6 on 2023-11-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('date_of_visit', models.DateField()),
                ('action', models.CharField()),
                ('Allergies', models.TextField(default='enter')),
                ('MedicalConditions', models.TextField(default='enter')),
                ('PreviouDentalTreatments', models.TextField(default='enter')),
                ('DentalConditions', models.TextField(default='enter')),
                ('DentalHygieneHabits', models.TextField(default='enter')),
                ('image', models.ImageField(max_length=200, null=True, upload_to='medicalhistory/images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
