# Generated by Django 4.2.6 on 2023-11-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
