# Generated by Django 4.2.6 on 2023-11-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0002_alter_medicalhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='action',
            field=models.CharField(),
        ),
    ]
