# Generated by Django 4.2.6 on 2023-11-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0003_alter_medicalhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='date_of_visit',
            field=models.DateField(),
        ),
    ]
