# Generated by Django 4.2.6 on 2023-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0004_alter_medicalhistory_date_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='Allergies',
            field=models.CharField(default='enter'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='DentalConditions',
            field=models.TextField(default='enter'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='DentalHygieneHabits',
            field=models.TextField(default='enter'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='MedicalConditions',
            field=models.TextField(default='enter'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='PreviouDentalTreatments',
            field=models.TextField(default='enter'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='medicalhistory/images/'),
        ),
    ]
