# Generated by Django 4.2.6 on 2023-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0005_medicalhistory_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='Allergies',
            field=models.TextField(default='enter'),
        ),
    ]
