# Generated by Django 4.2.6 on 2023-11-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0006_alter_medicalhistory_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='action',
        ),
    ]
