# Generated by Django 4.2.6 on 2023-11-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='image',
            new_name='case',
        ),
    ]
