# Generated by Django 4.2.6 on 2023-11-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_image_cases_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='image',
            new_name='certificate',
        ),
    ]
